### ISSUE TITLE
Unable to get a new project with AR XML tag to run 

### ISSUE THREAD

**Issue by IndieHobFreeDev** [EddyVerbruggen/nativescript-ar#114]
### Which platform(s) does your issue occur on?
- iOS on MAC running on iPhone 6S

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.0.2
- packge.json
{
  "name": "@nativescript/template-hello-world-ts",
  "main": "app/app.ts",
  "version": "8.0.6",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "files": [
    "app",
    "App_Resources",
    "hooks",
    "tools",
    "!tools/assets",
    ".editorconfig",
    "references.d.ts",
    "tsconfig.json"
  ],
  "keywords": [
    "nativescript",
    "mobile",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "homepage": "https://github.com/NativeScript/nativescript-app-templates",
  "dependencies": {
    "@nativescript/core": "~8.0.0",
    "@nativescript/theme": "~3.0.1",
    "nativescript-ar": "^1.1.0"
  },
  "devDependencies": {
    "@nativescript/ios": "8.0.0",
    "@nativescript/types": "~8.0.0",
    "@nativescript/webpack": "beta",
    "typescript": "~4.0.0"
  },
  "private": "true",
  "readme": "NativeScript Application"
}

- -------------

### Please, tell us how to recreate the issue in as much detail as possible. 
Created a hello world template TS project and then added the ns-AR plugin using "tns plugin add nativescript-ar". modified the main-page.xml to 
<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:AR="nativescript-ar" navigatingTo="navigatingTo">
    <ActionBar title="My App" icon="" />
  <GridLayout rows="auto, *" columns="*" class="p-20">
    <Label text="AR FTW!" class="t-20 text-center" textWrap="true"/>
    <AR:AR
        row="1"
        debugLevel="FEATURE_POINTS"
        detectPlanes="true"
        showStatistics="true"
        planeOpacity="0.2"
        arLoaded="arLoaded"
        planeTapped="planeTapped" />
  </GridLayout>
</Page>

run the project using tns run ios and it gave the following errors
-----
Searching for devices...
Preparing project...
webpack is watching the files...
asset vendor.js 6.22 MiB [compared for emit] (name: vendor) (id hint: defaultVendor)
asset bundle.js 345 KiB [compared for emit] (name: bundle)
asset runtime.js 86.4 KiB [compared for emit] (name: runtime)
asset tns_modules/inspector_modules.js 1.26 KiB [compared for emit] (name: tns_modules/inspector_modules)
Entrypoint bundle 6.64 MiB = runtime.js 86.4 KiB vendor.js 6.22 MiB bundle.js 345 KiB
Entrypoint tns_modules/inspector_modules 6.3 MiB = runtime.js 86.4 KiB vendor.js 6.22 MiB tns_modules/inspector_modules.js 1.26 KiB
runtime modules 24.7 KiB 12 modules
orphan modules 356 bytes [orphan] 6 modules
modules by path ./node_modules/ 2.36 MiB 312 modules
modules by path ./app/ 125 KiB
  modules by path ./app/*.ts 5.69 KiB 3 modules
  modules by path ./app/*.xml 1.13 KiB
    ./app/app-root.xml 239 bytes [optional] [built] [code generated]
    ./app/main-page.xml 918 bytes [optional] [built] [code generated]
  ./app/__@nativescript_webpack_virtual_entry_typescript__ 236 bytes [built] [code generated]
  ./app/app.css 118 KiB [built] [code generated]
  ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ 270 bytes [built] [code generated]
external "~/package.json" 42 bytes [optional] [built] [code generated]

ERROR in ./node_modules/nativescript-ar/ar-common.js 3:21-64
Module not found: Error: Can't resolve 'tns-core-modules/ui/content-view' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./node_modules/nativescript-ar/ar.ios.js 7:18-40
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/ar-common.js 4:13-53
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/view' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./node_modules/nativescript-ar/ar.ios.js 7:18-40
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/ar-common.js 5:18-63
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/view-base' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./node_modules/nativescript-ar/ar.ios.js 7:18-40
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/ar.ios.js 3:18-57
Module not found: Error: Can't resolve 'tns-core-modules/application' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/ar.ios.js 4:21-61
Module not found: Error: Can't resolve 'tns-core-modules/image-source' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/ar.ios.js 5:17-53
Module not found: Error: Can't resolve 'tns-core-modules/platform' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/ar.ios.js 6:13-51
Module not found: Error: Can't resolve 'tns-core-modules/utils/lazy' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/nodes/ios/arimage.js 3:21-61
Module not found: Error: Can't resolve 'tns-core-modules/image-source' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar/nodes/ios'
 @ ./node_modules/nativescript-ar/ar.ios.js 10:16-46
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/nodes/ios/aruiview.js 3:17-53
Module not found: Error: Can't resolve 'tns-core-modules/platform' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar/nodes/ios'
 @ ./node_modules/nativescript-ar/ar.ios.js 17:17-48
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/nodes/ios/aruiview.js 4:13-53
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/view' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar/nodes/ios'
 @ ./node_modules/nativescript-ar/ar.ios.js 17:17-48
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/nodes/ios/arvideo.js 3:18-57
Module not found: Error: Can't resolve 'tns-core-modules/application' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar/nodes/ios'
 @ ./node_modules/nativescript-ar/ar.ios.js 18:16-46
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

11 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.46.0 compiled with 11 errors in 8225 ms
Webpack compilation complete. Watching for file changes.
Updating runtime package.json with configuration values...
Project successfully prepared (ios)
Issues checking in progress...
File change detected. Starting incremental webpack compilation...
assets by status 6.64 MiB [cached] 4 assets
Entrypoint bundle 6.64 MiB = runtime.js 86.4 KiB vendor.js 6.22 MiB bundle.js 345 KiB
Entrypoint tns_modules/inspector_modules 6.3 MiB = runtime.js 86.4 KiB vendor.js 6.22 MiB tns_modules/inspector_modules.js 1.26 KiB
cached modules 2.48 MiB (javascript) 24.7 KiB (runtime) [cached] 364 modules
javascript modules 506 bytes
  ./app/__@nativescript_webpack_virtual_entry_typescript__ 236 bytes [built]
  ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ 270 bytes [built]

ERROR in ./node_modules/nativescript-ar/ar-common.js 3:21-64
Module not found: Error: Can't resolve 'tns-core-modules/ui/content-view' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./node_modules/nativescript-ar/ar.ios.js 7:18-40
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/ar-common.js 4:13-53
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/view' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./node_modules/nativescript-ar/ar.ios.js 7:18-40
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/ar-common.js 5:18-63
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/view-base' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./node_modules/nativescript-ar/ar.ios.js 7:18-40
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/ar.ios.js 3:18-57
Module not found: Error: Can't resolve 'tns-core-modules/application' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/ar.ios.js 4:21-61
Module not found: Error: Can't resolve 'tns-core-modules/image-source' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/ar.ios.js 5:17-53
Module not found: Error: Can't resolve 'tns-core-modules/platform' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/ar.ios.js 6:13-51
Module not found: Error: Can't resolve 'tns-core-modules/utils/lazy' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar'
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/nodes/ios/arimage.js 3:21-61
Module not found: Error: Can't resolve 'tns-core-modules/image-source' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar/nodes/ios'
 @ ./node_modules/nativescript-ar/ar.ios.js 10:16-46
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/nodes/ios/aruiview.js 3:17-53
Module not found: Error: Can't resolve 'tns-core-modules/platform' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar/nodes/ios'
 @ ./node_modules/nativescript-ar/ar.ios.js 17:17-48
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/nodes/ios/aruiview.js 4:13-53
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/view' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar/nodes/ios'
 @ ./node_modules/nativescript-ar/ar.ios.js 17:17-48
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

ERROR in ./node_modules/nativescript-ar/nodes/ios/arvideo.js 3:18-57
Module not found: Error: Can't resolve 'tns-core-modules/application' in '/Users/pkumbhat/gvf/testar/node_modules/nativescript-ar/nodes/ios'
 @ ./node_modules/nativescript-ar/ar.ios.js 18:16-46
 @ ./app/main-page.xml 3:7-33 7:7-33
 @ ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ ./main-page.xml
 @ ./app/__@nativescript_webpack_virtual_entry_typescript__ 3:16-101

11 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.46.0 compiled with 11 errors in 2938 ms
Webpack compilation complete. Watching for file changes.
Issues checking in progress...
No issues found.
Restarting application on device 2a7ba4a24fcd38d7baf98aba6053f767133120db...

NativeScript encountered a fatal error: Uncaught Error: Building UI from XML. @app-root.xml:1:1
 > Building UI from XML. @main-page.xml:6:5
   > Module 'nativescript-ar' not found for element 'nativescript-ar:AR'.
   > Cannot find module 'tns-core-modules/application'
 at 
	ScopeError(file:///app/vendor.js:44957:9)
	at SourceError(file:///app/vendor.js:44964:9)
	at (file:///app/vendor.js:17981:17)
	at (file:///app/vendor.js:17960:32)
	at (file:///app/vendor.js:46704:13)
	at EasySAXParser.parse(file:///app/vendor.js:11921:23)
	at parse(file:///app/vendor.js:46747:22)
	at parse(file:///app/vendor.js:17969:27)
	at parseInternal(file:///app/vendor.js:17934:11)
	at loadInternal(file:///app/vendor.js:17847:27)
	at createViewFromEntry(file:///app/vendor.js:17789:41)
	at createRootView(file:///app/vendor.js:1878:73)
	at setWindowContent(file:///app/vendor.js:1819:26)
	at notifyAppStarted(file:///app/vendor.js:1730:22)
	at didFinishLaunchingWithOptions(file:///app/vendor.js:1713:14)
	at NotificationObserver.o<…>

-----

### Is there any code involved? 
[Archive.zip](https://github.com/EddyVerbruggen/nativescript-ar/files/6872451/Archive.zip)

**Comment by IndieHobFreeDev** [comment]
Resolved it by updating tns core modules 
and then by opening the xcode workspace and setting "Do not embed" for TNSWidgets.framework in "General tab" of the testar target.
